[package]
name = "air"
version.workspace = true
edition.workspace = true

[dependencies]
algebra.workspace = true
p3_field.workspace = true
tracing.workspace = true
fiat-shamir.workspace = true
pcs.workspace = true
sumcheck.workspace = true

[dev-dependencies]
p3_koala_bear.workspace = true