[package]
name = "fiat-shamir"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
utils.workspace = true
p3-field.workspace = true
rand.workspace = true
rayon.workspace = true
tracing.workspace = true
