[package]
name = "merkle-tree"
version.workspace = true
edition.workspace = true

[dependencies]
algebra.workspace = true
rayon.workspace = true
sha3.workspace = true
tracing.workspace = true

[dev-dependencies]
rand.workspace = true
