[package]
name = "merkle-tree"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
rayon.workspace = true
sha3.workspace = true
tracing.workspace = true
utils.workspace = true

[dev-dependencies]
rand.workspace = true
