[package]
name = "cuda-engine"
version.workspace = true
edition.workspace = true

[dependencies]
cudarc.workspace = true
arithmetic-circuit.workspace = true
tracing.workspace = true
p3-field.workspace = true
utils.workspace = true
derive_more.workspace = true
p3-koala-bear.workspace = true