[package]
name = "utils"
version.workspace = true
edition.workspace = true

[dependencies]
p3-field.workspace = true
rand.workspace = true
rayon.workspace = true
sha3.workspace = true
regex.workspace = true
cudarc.workspace = true

[dev-dependencies]
p3-koala-bear.workspace = true