[package]
name = "cuda-bindings"
version.workspace = true
edition.workspace = true

[dependencies]
cudarc.workspace = true
tracing.workspace = true
p3-field.workspace = true
utils.workspace = true
cuda-engine.workspace = true

[dev-dependencies]
p3-koala-bear.workspace = true
rayon.workspace = true
rand.workspace = true