[package]
name = "cuda-bindings"
version.workspace = true
edition.workspace = true

[dependencies]
cudarc.workspace = true
rayon.workspace = true
tracing.workspace = true
p3-field.workspace = true
algebra.workspace = true

[dev-dependencies]
sha3.workspace = true
rand.workspace = true
p3-koala-bear.workspace = true
