[package]
name = "arithmetic-circuit"
version.workspace = true
edition.workspace = true

[dependencies]
p3-field.workspace = true
rand.workspace = true

[dev-dependencies]
p3-koala-bear.workspace = true
utils.workspace = true
